# Generated by Django 2.2.6 on 2021-06-30 12:44

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210629_1157'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('following')), name='impossible_subscribe_yourself'),
        ),
    ]
